### PR TITLE
Website Dev : Small Changes

### PR DESCRIPTION
**Pull request by MidouWebDev**
Deleted the Discord Login Button
Renamed Features to Home
Edited some Meta Tags

### CODE REVIEW

**Review by j-dogcoder — CHANGES_REQUESTED** [review]
Hey @MidouWebDev! Can we have the discord, GitHub, and designed by footer all on one line?

**Comment by j-dogcoder** [comment]
Screen Shot 2021-08-05 at 3 51 20 PM
 
Also, doesn't that look weird? It's only on the commands page.

**Comment by MidouWebDev** [comment]
@j-dogcoder can we keep it for the next PR please ? Just merge it, i am going to work on it tomorrow by adding footer to all  the pages

**Comment by j-dogcoder** [comment]
Sounds good.

**Comment by j-dogcoder** [comment]
Can we fix the header issue though?

**Comment by MidouWebDev** [comment]
@j-dogcoder thanks

**Comment by j-dogcoder** [comment]
@MidouWebDev

**Review by j-dogcoder — APPROVED** [review]

**Pull request merged**
