### PR TITLE
We can launch the website now !

### LINKED ISSUE #78: Structure the Folder ( For launching the new website )

### PR DESCRIPTION
**Pull request by MidouWebDev**
🔥 
Fixed #78 and #79

### CODE REVIEW

**Comment by MidouWebDev** [comment]
@j-dogcoder Once this PR is merged, you can merge the #61 
We can move now definitely to the new website ! 🔥

**Comment by j-dogcoder** [comment]
Closed by #61

**Comment by MidouWebDev** [comment]
@j-dogcoder it should be merged

**Comment by j-dogcoder** [comment]
That is what the other PR is for, I am reviewing it now.

**Comment by MidouWebDev** [comment]
but these commits aren't merged  @j-dogcoder

**Pull request merged**
