### PR TITLE
:lipstick: New coming soon page

### PR DESCRIPTION
**Pull request by j-dogcoder**

### CODE REVIEW

**Comment by j-dogcoder** [comment]
@MidouWebDev I was think that for coming soon things, we can just redirect to this page.

**Review by MidouWebDev — CHANGES_REQUESTED** [review]
Good job, it looks good but we can't see the text very well so i suggest to add a background-color : #2C2F33 and color: white to the .bgimg element

**Comment by MidouWebDev** [comment]
@j-dogcoder

**Comment by j-dogcoder** [comment]
@MidouWebDev It doesn't change anything.

**Comment by MidouWebDev** [comment]
@j-dogcoder how ?

**Pull request merged**
