### PR TITLE
Switching to react

### PR DESCRIPTION
**Pull request by MidouWebDev**
cd heptagram.xyz
npm install
npm start

See preview

I worked on Home Page, Privacy Policy and TOS

### CODE REVIEW

**Comment by MidouWebDev** [comment]
@j-dogcoder why a draft ?
I worked on a part of the work and @Panquesito7 will complete.

**Comment by j-dogcoder** [comment]
Is this ready to be merged @MidouWebDev?

**Comment by MidouWebDev** [comment]
@j-dogcoder yes, there is a big part of the work that i and @Panquesito7 will try to finish out.
Let's say it is a v.0.5

**Comment by MidouWebDev** [comment]
@Panquesito7 it is a work on progress. There is some bugs that we will fix.

We : @Panquesito7 @MidouWebDev @anubhav06

**Pull request merged**
