### PR TITLE
React switch [WIP]

### PR DESCRIPTION
**Pull request by j-dogcoder**
# Pull Request

## Related Issue

Closes #54 

## Scope

Did you remember to update the `package.json` version number?

- [ ] Major Version Update: X.\_.\_ (for complete code refactors, or large PRs that adjust most of the codebase)
- [ ] Minor Version Update: \_.X.\_ (for the addition of new commands)
- [ ] Patch Version Update: \_.\_.X (for bug fixes _in the code_.)
- [x] No Version Update: \_.\_.\_ (no version update for additions to tests, documentation, or anything that isn't end-user facing.)

## Documentation

For _any_ version updates, please verify if the documentation page needs an update. If it does, please create an issue to ensure it is not forgotten.

- [x] My contribution does NOT require a documentation update.
- [ ] My contribution DOES require a documentation update.

### CODE REVIEW

**Comment by MidouWebDev** [comment]
We didn't finish that so that we can create a PR !
There is a lot of things to do.

**Comment by MidouWebDev** [comment]
@j-dogcoder 
I think we should close it, once we will need it i am going to tell you (even if it is a draft).
Because once we merge this, we are not going to keep the live version (HTML, CSS,JS) hosted.

**Comment by j-dogcoder** [comment]
Hey, let's keep this as a draft

**Comment by MidouWebDev** [comment]
> SonarCloud Quality Gate failed.    Quality Gate failed
> 
> [Bug](https://sonarcloud.io/project/issues?id=Heptagram-Bot_heptagram.xyz&pullRequest=61&resolved=false&types=BUG) [C](https://sonarcloud.io/project/issues?id=Heptagram-Bot_heptagram.xyz&pullRequest=61&resolved=false&types=BUG) [2 Bugs](https://sonarcloud.io/project/issues?id=Heptagram-Bot_heptagram.xyz&pullRequest=61&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=Heptagram-Bot_heptagram.xyz&pullRequest=61&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=Heptagram-Bot_heptagram.xyz&pullRequest=61&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=Heptagram-Bot_heptagram.xyz&pullRequest=61&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=Heptagram-Bot_heptagram.xyz&pullRequest=61&resolved=false&types=SECURITY_HOTSPOT) [E](https://sonarcloud.io/project/security_hotspots?id=Heptagram-Bot_heptagram.xyz&pullRequest=61&resolved=false&types=SECURITY_HOTSPOT) [2 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=Heptagram-Bot_heptagram.xyz&pullRequest=61&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=Heptagram-Bot_heptagram.xyz&pullRequest=61&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=Heptagram-Bot_heptagram.xyz&pullRequest=61&resolved=false&types=CODE_SMELL) [33 Code Smells](https://sonarcloud.io/project/issues?id=Heptagram-Bot_heptagram.xyz&pullRequest=61&resolved=false&types=CODE_SMELL)
> 
> [No Coverage information](https://sonarcloud.io/component_measures?id=Heptagram-Bot_heptagram.xyz&pullRequest=61) No Coverage information [](https://sonarcloud.io/component_measures?id=Heptagram-Bot_heptagram.xyz&pullRequest=61&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=Heptagram-Bot_heptagram.xyz&pullRequest=61&metric=new_duplicated_lines_density&view=list)

@j-dogcoder I fixed the bugs + security hotspots issues in the PR i am going to create now.
Can you merge it and run again the bot ?
Thanks !

**Comment by j-dogcoder** [comment]
Is this ready for review @MidouWebDev?

**Comment by MidouWebDev** [comment]
> Is this ready for review @MidouWebDev?

Not yet.

**Comment by MidouWebDev** [comment]
@j-dogcoder #80 Should be merged

**Review by MidouWebDev — COMMENTED** [review]
@j-dogcoder 
The latest changes that should be added are at #80 
Once #80 is merged, this PR could be merged

**Comment by j-dogcoder** [comment]
**I am merging this one, which is the same as 80.**

**Pull request merged**
