### PR TITLE
Website Dev : Fixed Accessibility Issues

### PR DESCRIPTION
**Pull request by MidouWebDev**
The text in 404.html and coming-soon.html is visible now !

### CODE REVIEW

**Comment by j-dogcoder** [comment]
Was the login with discord issue fixed @MidouWebDev?

**Comment by j-dogcoder** [comment]
It's still broken on the site preview.

**Comment by MidouWebDev** [comment]
Oh i fixed it !!

**Comment by j-dogcoder** [comment]
Did you see the vercel preview?

**Review by j-dogcoder — APPROVED** [review]

**Pull request merged**
