### PR TITLE
 add health-check route

### LINKED ISSUE #126: Health Check endpoint
Hey @Heptagram-Bot-Project/website-team , can we add a Health Check endpoint `/health` to the website, returning a simple `200` status?

[https://microservices.io/patterns/observability/health-check-api.html](https://microservices.io/patterns/observability/health-check-api.html
)[https://www.ibm.com/garage/method/practices/manage/health-check-apis/](https://www.ibm.com/garage/method/practices/manage/health-check-apis/)

### PR DESCRIPTION
**Pull request by sancodes**
work on #126 

- add route `/health-check` that links to `HealthCheckPage.js`

### CODE REVIEW

**Review by jaspermayone — CHANGES_REQUESTED** [review]
website – Deployment Overview Safari app P6aIuftJ

Hey @sancodes, NPM is throwing an error when trying to build the project.

**Comment by sancodes** [comment]
@j-dogcoder had to downgrade the react-router-dom to version less than 6.0.0. 

In react-router-dom `v6` it looks like `Switch` has been replaced with`Routes`

**Comment by j-dogcoder** [comment]
I will trigger a re-deploy

**Review by jaspermayone — CHANGES_REQUESTED** [review]
@sancodes This looks good mostly. See my below comments.

**Comment by j-dogcoder** [comment]
We want it returning a status code, not a webpage

**Comment by j-dogcoder** [comment]
Something similar to 

```
Route.add(‘/api/v1/healthcheck’, Method=’GET’) {
    If (userdb.connect() == “Successful”) {
        headers={‘http_status’:200, ‘cache-control’:  ‘no-cache’}
        body={‘status’: ‘available’}
        }
    Else {
        headers={‘http_status’:500, ‘cache-control’:  ‘no-cache’}
        body={‘status’: ‘unavailable’}
        }
}
```

**Comment by sancodes** [comment]
@j-dogcoder 

> Route.add(‘/api/v1/healthcheck’, Method=’GET’) {
>     If (userdb.connect() == “Successful”) {
>         headers={‘http_status’:200, ‘cache-control’:  ‘no-cache’}
>         body={‘status’: ‘available’}
>         }
>     Else {
>         headers={‘http_status’:500, ‘cache-control’:  ‘no-cache’}
>         body={‘status’: ‘unavailable’}
>         }

isnt that something you'd do in a backend? 
i tried looking around, I cant seem to be able in returning just a `status code` and `json`object. 
The best I can come up here is just returning a webpage, with the status code. 

Maybe you can guide me? 

I'm limited to React knowledge. Sorry.

**Comment by j-dogcoder** [comment]
Hey @sancodes, this is not my area of expertise. I will ping the @Heptagram-Bot-Project/website-team to see if anyone can give you guidance.

**Review by jaspermayone — APPROVED** [review]
Finished this up for you @sancodes! (It was a simple fix.). 

LGTM 🎉

**Pull request merged**
